display:
  cycle: true
  inverted: false
  orientation: 90
ticker:
  currency: bitcoin,ethereum,cardano,algorand,monero
  exchange: default
  fiatcurrency: usd
  sparklinedays: 28
  updatefrequency: 5
